### ISSUE TITLE
你好，你是用在什么环境下运行的啊。我在CentOS下运行这个仓库，python setup.py build_ext --inplace 这一步总是报错

### ISSUE THREAD

**Issue by beilyLan** [wac81/vits_chinese#5]
(vits) [root@imyfone-daihuanhao monotonic_align_copy]# python setup.py build_ext --inplace
error: could not create 'monotonic_align_copy/core.cpython-310-x86_64-linux-gnu.so': No such file or directory

**Comment by beilyLan** [comment]
文件夹名字错误

**Comment by wac81** [comment]
ubuntu 1804

**Comment by sunnnnnnnny** [comment]
@beilyLan  ref it [](https://github.com/jaywalnut310/glow-tts/issues/62)

**Comment by sunnnnnnnny** [comment]
@beilyLan  ref it https://github.com/jaywalnut310/glow-tts/issues/62

**Comment by p1an-lin-jung** [comment]
在glow-tts里的解决方法是，假设你已经在monotonic_align_copy目录下，那你再在这里创建一个monotonic_align_copy的同名子目录，然后就运行成功了

**Comment by gupt29** [comment]
> ubuntu 1804
Do  i need 18.04 to resolve this. Can't we do this on 20 or 22??
